### ISSUE TITLE
missing features in yumex-nextgen

### ISSUE THREAD

**Issue by NiceandGently** [timlau/yumex#27]
I really miss some features from old yumex which prevent me to use yum-nextgen as standalone w/o normal yumex.
1. Buttons to select/deselect all updates (Must)
2. Option to reinstall or downgrade a package (Must)
3. The categories screen, where you can quick select packages from a local or external repo w/o doing a package search. (NiceToHave)

offtopic on:
Why using ugly client side decorations design in dnf version?
Gnome will use gnome-software, i thought your intention was to develop a package-manager for traditional desktops with windows decorations.
Do you really expect that much gnome users will use yumex when they have click-bunti
gnome-software?
And if you really want to use CSD design, please add minimize/maximum buttons.
Thank you
offtopic off.

Anyway, thanks for all your work with yumex, we need it as an alternative.

PS: I'm maintaining Mate in fedora

**Comment by NiceandGently** [comment]
Using http://www.webupd8.org/2014/08/how-to-disable-gtk3-client-side.html is a hack (and don't work in fedora) which i can't use as fedora maintainer for mate desktop.
I'm still wondering why you think a GTK3 application needs csd for displaying correct inside gnome.
Every normal GTK3 application with metacity decoration works well under gnome.
On the other side all other desktops has problems to display csd apps well, for example shadows and and and........
And for me the new design isn't very intuitive to use, with the old design you saw most option in one screen, i'm in doupt that new users will find options, etc. with yumex-dnf csd version.
Anyways, your decision.

best regards

**Comment by timlau** [comment]
@NiceandGently yumex-dnf-4.0.10 will now only use a headerbar by default if running gnome.
In other DE's it will use a toolbar in a decorated window.

https://copr.fedoraproject.org/coprs/timlau/yumex-dnf/

**Comment by NiceandGently** [comment]
@timlau 
Thank you for reverting csd, no need of it since gnome 3.16 style all applications with server-side-decorations.
Will we see yumex-dnf in f22 ?

**Comment by timlau** [comment]
@NiceandGently, my plan is to submit it for package review very soon
