### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by FDiskas** [timlau/yumex#29]
`
failure: repodata/repomd.xml from docker-main-repo: [Errno 256] No more mirrors to try.
https://yum.dockerproject.org/repo/main/fedora/22/repodata/repomd.xml: [Errno 14] HTTPS Error 503 - Service Unavailable
https://yum.dockerproject.org/repo/main/fedora/22/repodata/repomd.xml: [Errno 14] HTTPS Error 503 - Service Unavailable
https://yum.dockerproject.org/repo/main/fedora/22/repodata/repomd.xml: [Errno 14] HTTPS Error 503 - Service Unavailable
https://yum.dockerproject.org/repo/main/fedora/22/repodata/repomd.xml: [Errno 14] HTTPS Error 503 - Service Unavailable
`

**Comment by timlau** [comment]
Look like docker-main-repo repository is offline
