### ISSUE TITLE
Clean Unused Requirements as default

### ISSUE THREAD

**Issue by brinskoj** [timlau/yumex#5]
version 3.0.10
running on Fuduntu

In preferences, checkbox "Clean unused requirements as default".
Click OK.
remove_requirements = 1 is written to the last line in ~/.config/yumex/yumex.conf
Open the preferences dialogue and the checkbox for Clean unused requirements is no longer checked.
Check the box and press OK.
remove_requirements = 1 is written to the last line in ~/.config/yumex/yumex.conf  (another line same as before, so now there are multiple lines that say "remove_requirements = 1")
All other checkboxes in the preferences persist as normal.

This is what I am experiencing. Please advise.

**Comment by timlau** [comment]
fixed 

https://github.com/timlau/yumex/commit/48027f5ffb4ef66a4d483eac25811b164aec9f24
